version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: store_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - store_network

volumes:
  postgres_data:

networks:
  store_network:
